#!/bin/sh

# This script adjusts Linux kernel parameters to reduce buffer
# overflow in the kernel.

# Increase maximum socket buffer sizes.  Ensemble will then be able
# to request larger sizes.
echo 1000000 >/proc/sys/net/core/rmem_max
echo 1000000 >/proc/sys/net/core/wmem_max

# Increase the ethernet transmit queue length to prevent messages
# from being dropped at transmit.
ifconfig eth0 txqueuelen 1000

# Increase the number of rx packets that can be queued
echo 10000 >/proc/sys/net/core/netdev_max_backlog
